# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 914b1dd045c5ca5d152b621bc745970ef70f41eb48c0cf9adf75af00a8cc934b385a1017b9a987f78ba3962aef1095413669366632844ca2283fd9d36875cc56

test:
  secret_key_base: 5cb6c3d77cc636e6b05025417972dd630c708bafdb24b419dbd33853663e3d1aa194a34c20e3e7312c78de829513d88b18b70a20a13ccf8ab0339194e82aaa46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
